update to pyopenssl 16.0.0
https://github.com/hynek/pyopenssl/blob/b62041bdf17/CHANGELOG.rst

The update to python-six is necessary to avoid traceback with error:

    ImportError: cannot import name indexbytes