upgrade to duoauthproxy 2.10.1 and resolve breaking changes
Upstream authproxy has new dependencies:

* Add `procps` package since install script now requires `ps -p`.

Upstream authproxy introduced breaking changes since 2.9:

* Authproxy now absolutely needs to write to a logfile.

* Authproxy no longer has the `-c CONFIG` option.
  The path to config is now hard-coded.

Rebase on Centos instead of Alpine.

* Authproxy now requires `FIPS_mode` that is not in LibreSSL.
  https://marc.info/?l=openbsd-misc&m=139819485423701&w=2

  On Alpine (which has LibreSSL instead of OpenSSL),
  authproxy fails with:

  ```
  Traceback (most recent call last):
    File "/opt/duoauthproxy/bin/authproxy", line 21, in <module>
      application = proxy.create_application(args=sys.argv)

    File "/opt/duoauthproxy/usr/local/lib/python2.7/site-packages/duoauthproxy/proxy.py",
    line 186, in create_application
      fips_mode = fips_manager.status()

    File "/opt/duoauthproxy/usr/local/lib/python2.7/site-packages/duoauthproxy/lib/fips_manager.py",
    line 42, in status
      return OPENSSL_LIB.FIPS_mode()

  AttributeError: 'module' object has no attribute 'FIPS_mode'
  ```